# Generated by Django 5.0.6 on 2024-07-16 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='guess_can_pause',
            new_name='guest_can_pause',
        ),
    ]
